import process from "node:process";
import { createAdminPasswordRecord, fingerprintAdminAuthSecret } from "../../src/server/cloudflare/admin-auth-crypto.server.ts";
function required(name:string){const value=process.env[name]?.trim();if(!value)throw new Error(`${name} is required.`);return value;}
function opaque(name:string){const value=process.env[name];if(!value)throw new Error(`${name} is required.`);return value;}
function sql(value:string){return `'${value.replaceAll("'","''")}'`;}
const email=required("TRETNIX_ADMIN_EMAIL").toLowerCase();const password=opaque("TRETNIX_ADMIN_PASSWORD");const pepper=required("TRETNIX_ADMIN_AUTH_PEPPER");
if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||email.length>160)throw new Error("TRETNIX_ADMIN_EMAIL must be a valid email address up to 160 characters.");
if(password.length<12||password.length>128)throw new Error("TRETNIX_ADMIN_PASSWORD must contain 12 to 128 characters.");
if(pepper.length<32)throw new Error("TRETNIX_ADMIN_AUTH_PEPPER must contain at least 32 characters.");
const record=await createAdminPasswordRecord(password,pepper);const now=new Date().toISOString();const id=crypto.randomUUID();process.stderr.write(`Tretnix admin pepper fingerprint (SHA-256/16 hex): ${await fingerprintAdminAuthSecret(pepper)}\n`);process.stdout.write("-- Generated Tretnix native admin record. Contains no plaintext password or pepper.\n");process.stdout.write(`INSERT INTO admin_users(id,email,email_normalized,password_scheme,password_iterations,password_salt,password_hash,status,created_at,updated_at,last_login_at) VALUES(${sql(id)},${sql(email)},${sql(email)},${sql(record.scheme)},${record.passwordWorkFactor},${sql(record.salt)},${sql(record.passwordHash)},'active',${sql(now)},${sql(now)},NULL) ON CONFLICT(email_normalized) DO UPDATE SET email=excluded.email,password_scheme=excluded.password_scheme,password_iterations=excluded.password_iterations,password_salt=excluded.password_salt,password_hash=excluded.password_hash,status='active',updated_at=excluded.updated_at;\n`);process.stdout.write(`DELETE FROM admin_sessions WHERE user_id=(SELECT id FROM admin_users WHERE email_normalized=${sql(email)});\n`);
